Completed react-context exercise.
sharon-tieu/rc0822-code-solutions pull request #136
Opened 2022-11-04 22:51 UTC by sharon-tieu

https://user-images.githubusercontent.com/103021766/200085993-c4fbe690-86a4-4c65-9904-0c8bc5510b5c.mov

2022-11-04 23:05 UTC, TimelikeClosure requested changes

2022-11-04 23:05 UTC, TimelikeClosure commented on react-context/client/components/auth-form.jsx
> +AuthForm.contextType = AppContext;
Only set a `contextType` on components that directly use its data.

2022-11-04 23:08 UTC, TimelikeClosure requested changes

2022-11-04 23:08 UTC, TimelikeClosure commented on react-context/client/components/page-container.jsx
> +PageContainer.contextType = AppContext;
Only set a `contextType` on components that directly use its data.

2022-11-22 19:46 UTC, scbowler approved these changes
Looks good! 👍

2022-11-22 20:21 UTC, merged